### ISSUE TITLE
How do i open the form in the deployment

### ISSUE THREAD

**Issue by tijs** [mopinion/mopinion-sdk-react-native#10]
I have setup the MopinionDeployment component wanting to display it in a modal. While i see the deployment initialises in my logs it does not display anything in my app. From what i can tell this is because the deployment contains a list of forms for which the `open` attribute should be `true`. Problem is; i don't see any way to set this value to true in the API for the deployment component. To be honest i would expect the form to be visible by default...

Looking at my logs the deployment is fetched correctly and the forms array looks like this:

```
forms: {
   acb1234: {open: false, instance: "0.9acb1234"}
}
```

(i have changed the id's for this example)

How do i correctly trigger the form display?

**Comment by Anwardo** [comment]
Hi @tijs. It seems your issue is that you're not calling one of the events linking to your specific form. Let me provide a more detailed example.

Say the following is your current app with our deployment component:

```
import React from 'react';
import { View } from 'react-native';
import { MopinionDeployment } from 'mopinion-react-native-sdk';

function App(props) {
  return (
    <View>
      <MopinionDeployment id="abc1234" />
    </View>
)
```

In this case the deployment would be fetched from the server and intialized but no forms will open until you actually trigger it manually by calling the `MopinionSDK` event emitter. You could do this either as a side-effect to a state/prop change or in any event handler. An example for when you would want to trigger a form right away (and you've setup a proactive type form in your deployment using the '_proactive' event):
```
import React, { useEffect } from 'react';
import { View } from 'react-native';
import { MopinionDeployment, MopinionSDK } from 'mopinion-react-native-sdk';

function App(props) {
  useEffect(() => {
    MopinionSDK.event('_proactive');
  }, []);

  return (
    <View>
      <MopinionDeployment id="abc1234" />
    </View>
)
```
This example would trigger your form on initial render. _Note that the difference between setting up a passive vs. a proactive type form is that a passive form will trigger any time all the conditions are true and the correlating event is a fired. While a proactive form will only show once per session (defined in your deployment) when all conditions are true and the event is fired._

Hope this clears it up a little bit for you! 🙂 

On a sidenote. It seems there was an issue with a named import for webviews. And we've also updated the path our webview controller was using to our latest webview forms url. Please update your package to the latest version.

**Comment by tijs** [comment]
@Anwardo thanks for the explanation, the difference between passive and active forms is not mentioned anywhere in the integration docs (here on GitHub for instance) so i would definitely add that as it's not really clear from the control panel. The form is indeed a passive form which should be triggered by a _button event. I thought i'd tried that already but i will upgrade and give it another shot.

Maybe a small feature request; it would be nice to have an overview of the releases here on GitHub too. That way it's easy to track releases and have a Changelog handy: https://github.com/mopinion/mopinion-sdk-react-native/releases

**Comment by Anwardo** [comment]
@tijs no problem. Hopefully it should clear up your issue. Agreed regarding documentation, it's something we will definitely be improving in the near future.

Good suggestion regarding Github releases. We started using Github releases starting v1.0.1. For earlier changes please refer to the changelog.

**Comment by tijs** [comment]
@Anwardo i just gave it another shot but still no luck displaying the form. It seems to initialise fine and i see the callback information come in but nothing is displayed.

The deployment seems to work:
```
{"appState": "active", "deployment": [{"clock": [Array], "date": [Array], "domain": "app.mopinion.com", "events": [Array], "formKey": "redacted", "percentage": null, "rule_id": "tnjac7KEFtjYckc", "session": 30, "target": [Array], "time": 0, "trigger": "passive", "webview": true}], "events": {"_button": [[Object]], "_force_5041daff977b64bf02699792d5b1f835b93d2547": [[Object]]}, "forms": {"redacted": {"instance": "0.r5i05qkwyj", "open": false}}, "screenshot": "", "userAgent": ""}
```
And it receives the `_button` event, as shown in the control panel:

<img width="1587" alt="Schermafbeelding 2019-12-23 om 14 51 31" src="https://user-images.githubusercontent.com/3108/71361765-3bfc4f00-2594-11ea-9c94-6ede51da63f4.png">

But nothing happens. What else can i try?

**Comment by tijs** [comment]
Changing the deployment to proactive and using the `_proactive` trigger does not help either.

**Comment by tijs** [comment]
I'm checking network traffic as well and while the JSON config above is returned from the deployment URL: https://mjolnir.mopinion.com/pastease/mobile/compact/[mopinion id here]

```
{"code": 200, "server_side": false, "deployment": [{"session": 30, "domain": "app.mopinion.com", "target": [], "clock": [], "percentage": null, "events": ["_button", "display", "redacted"], "date": [], "trigger": "passive", "time": 0, "formKey": "redacted", "webview": true, "rule_id": "tnjac7KEFtjYckc"}]}
```

the form is never fetched though as no other network request is done after this one.

**Comment by Anwardo** [comment]
I've found the cause of your issue. The event is being triggered except it's happening before the deployment has been fetched from the server/fully initialised. For now I've added an `onDeploymentLoaded` prop to the `MopinionDeployment` component in v1.1.0 of the package. This way you can hook into the callback and trigger the event after initialization. Usually events are triggered a while after the deployment has been loaded so we didn't encounter this as an issue yet. For now this fix should do fine. We might look into different ways in the future. Let me know if this fixes the problem for you 🙂 

Use it like so:
```
<MopinionDeployment
  onDeploymentLoaded={() => MopinionSDK.event('_button')}
/>
```

**Comment by tijs** [comment]
@Anwardo great that did the trick!

It seems you also open the form in a modal so i had to change our setup a bit to account for the built-in navigation but that works now as well; it's not possible to open just the form and provide the modal/navigation etc ourselves?

And, if that is not possible, how do i change the navigation header color? (see the screenshot attached)

![IMG_2446](https://user-images.githubusercontent.com/3108/71366191-99e36380-25a1-11ea-86d2-56ac7a70ebc9.PNG)

It seems the design edit features in the app allow me to change the styles for the form displayed in the modal but not the design of the modal itself. Is it possible to pass extra styling variables to the MopionionDeployment component so i can set the header color to the brand color i need?

**Comment by tijs** [comment]
@Anwardo also, how do i remove the 'powered by Mopinion' logo. I assume we can remove that since we are paying customers :)

**Comment by Piethot** [comment]
> @Anwardo also, how do i remove the 'powered by Mopinion' logo. I assume we can remove that since we are paying customers :)

Hi Tijs, with regard to the above request I have sent you a private message. Please see your email inbox.

**Comment by tijs** [comment]
@Piethot thanks for reaching out, got your message.

As for the navigation header color i think i still need help from @Anwardo or do you also know whether this is user configurable?

**Comment by Anwardo** [comment]
> It seems you also open the form in a modal so i had to change our setup a bit to account for the built-in navigation but that works now as well; it's not possible to open just the form and provide the modal/navigation etc ourselves?

Great that it works now 👍  

For now the form always opens in a modal. We will be adding different display types as well though in the future. However I'm not sure if embedded will be supported any time soon because they'll also have to be implemented into our native sdks.

It would be possible to load the form yourself inside a webview if you prefer but you would lose the flexibility of our deployment triggers.

With regards to styling the header, with a native form this would be done from the design area in our platform. However since you're using a webview the styles are not mapping over to the native part (the header). We'll make some changes to form configuration response so the header styles from webview forms will be mapped over to the native styles. The styles setup in the design area will be working from then on this wont require any changes in your code.

**Comment by Anwardo** [comment]
@tijs we just made the appropriate changes to the form configuration response. Your form should now respond to the background and text color styles setup in the design area.

**Comment by manuelabarca** [comment]
> I've found the cause of your issue. The event is being triggered except it's happening before the deployment has been fetched from the server/fully initialised. For now I've added an `onDeploymentLoaded` prop to the `MopinionDeployment` component in v1.1.0 of the package. This way you can hook into the callback and trigger the event after initialization. Usually events are triggered a while after the deployment has been loaded so we didn't encounter this as an issue yet. For now this fix should do fine. We might look into different ways in the future. Let me know if this fixes the problem for you 🙂
> 
> Use it like so:
> 
> ```
> <MopinionDeployment
>   onDeploymentLoaded={() => MopinionSDK.event('_button')}
> />
> ```

This work in 1.1.0 but in 1.2.0 doesn't work :s

**Comment by tijs** [comment]
@manuelabarca i'm using the 1.2.0 version currently and i do not seem to have this issue so for me this issue is closed. Maybe create a new bug if you still have this issue? This thread has become a but off-topic anyway :)
